name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ganatan
          THEME: transparent
